print("Hello! Welcome to the Band Name Generator.")
City_name = input("What's the name of the city you grew up in?\n")
Pet_name = input("What's your pet's name?\n")
print("Your band name could be " + City_name + " " + Pet_name)
print("Thank you for using the Band Name Generator!")
